name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
    - title: 💥 Breaking changes
      label: chore
    - title: 📰 Documentation
      label: documentation
    - title: 🚀 Features
      label: enhancement
    - title: 🐛 Bug Fixes
      label: bug
template: |
    ## Changes

    $CHANGES

    <!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->

    <!-- ALL-CONTRIBUTORS-LIST:END -->
