name: 'jest-coverage-report-action'
description: 'Reports total jest coverage'
author: 'Artiom Tretjakovas <artiom.tretjakovas2@gmail.com>'
branding:
    icon: 'activity'
    color: 'green'
inputs:
    github_token:
        required: true
        description: 'a github access token'
    test_script:
        required: false
        description: 'a custom npm script to test'
        default: npx jest --silent --coverage --json
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.github_token }}
        - ${{ inputs.test_script }}
        - ${{ inputs.directory }}
