name: Documentation deployment
on:
    push:
        paths:
            - 'docs/**'
        branches: [main]

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Begin job...
              uses: actions/checkout@v2

            - name: Use Node 12
              uses: actions/setup-node@v2
              with:
                  node-version: '12'
                  cache: 'npm'

            - name: Install deps (with cache)
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ./docs

            - name: Building
              run: npm run build
              working-directory: ./docs

            - name: Publishing to github-pages
              run: |
                  git config --global user.name 'Jest Coverage Report bot'
                  git config --global user.email 'covbot@users.noreply.github.com'
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run deploy
              working-directory: ./docs
              env:
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
                  NODE_ENV: 'production'
