on: [pull_request]

jobs:
    custom_test:
        runs-on: ubuntu-latest
        name: Test locally using act
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Test coverage
              uses: ./ # Uses an action in the root directory
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
